name: CI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: development
    env:
      DATABRICKS_HOST: ${{ secrets.DEPLOYMENT_TARGET_URL }}
      DATABRICKS_TOKEN: ${{ secrets.DEPLOYMENT_TARGET_TOKEN }}
      REPO_PATH: /Repos/Users/komatimurari67@gmail.com/test-databricks

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.8

    - name: Install Databricks CLI
      run: |
        pip install databricks-cli

    - name: Extract branch name
      id: extract_branch
      run: echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

    - name: Update Databricks Repository
      run: |
        databricks repos update --path "${{ env.REPO_PATH }}" --branch "${{ env.branch }}"
      env:
        DATABRICKS_HOST: ${{ secrets.DEPLOYMENT_TARGET_URL }}
        DATABRICKS_TOKEN: ${{ secrets.DEPLOYMENT_TARGET_TOKEN }}
